### ISSUE TITLE
Running on DWY100K

### ISSUE THREAD

**Issue by DexterZeng** [THU-KEG/KECG#3]
Hi, thank you very much for sharing the code! It has been really useful!

The code runs perfectly on DBP15K. However, when I ran it on DWY100K, an error emerged, "CUDA out of memory. Tried to allocate 11.44 GiB (GPU 0; ...; 9.49 GiB free...)", which is expected, since the size of DWY100K is much larger than DBP15K, and one GPU might not be enough. Consequently, I tried to use torch.nn.DataParallel to run it on multiple GPUs, while it reports "Runtime Error : sparse tensors do not have strides". I wonder how you altered the code to make it work on DWY100K?

Thank you very much for your time and I look forward to your reply.

**Comment by iamlockelightning** [comment]
Thank you for finding this repo useful!

Yes, the size of DWY100K is much larger than DBP15K, so one GPU is not enough.

But I think it still remains difficult in running this code on multiple GPUs. It's because I feed all triplets as one batch to train in the TransE part, so that I could train the whole model more efficiently (one round GAT -> TransE in one batch). torch.nn.DataParallel works only when the data is divided into batches, so it raises a Runtime Error.

I have tried to divide the triplets into batches so that I could use torch.nn.DataParallel to speed up, but it results in [multiple rounds GAT -> TransE in multiple batches, because one batch triplets need one round GAT], which may increase the time when memory copies the graph to other GPUs (especially a large graph). Another notable thing is the size of the sparse graph, which will cost much memory in graph attention (I haven't check whether one GPU is enough for graph attention on DWY100K or not).

By now the easiest way to run the code on DWY100K is to use CPU. But I'd be excited if you can PR a more efficient version of KECG.

**Comment by DexterZeng** [comment]
Hi, thank you very much for your detailed explanation!
Yes, I will try to explore how to improve the efficiency, but for now, running on CPU indeed works.

Thank you again for your response!

**Comment by DexterZeng** [comment]
Hi, just a quick question, what's the size of CPU you've used to run codes on DWY100K? Mine is 128G, which seems to be not enough...

Thank you for your time!

**Comment by iamlockelightning** [comment]
The memory size is 256G (220G is actually available).

If you're not able to run the code, you can decrease the negative sampling size, which won't harm the results so much.

**Comment by DexterZeng** [comment]
Thanks a lot!
